# Generated by Django 4.1.3 on 2022-11-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_famous_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famous_food',
            name='description',
        ),
    ]
